// Builds src/srcSet for files generated by `npm run images` (named <name>-<width>.webp).
export function responsive(name, widths) {
  return {
    src: `/images/${name}-${widths[0]}.webp`,
    srcSet: widths.map((width) => `/images/${name}-${width}.webp ${width}w`).join(', '),
  }
}
