// Turns full-size originals in /image-sources into responsive WebP files in /public/images.
// Usage: npm run images
// Add an entry below for each new image; widths are the srcset sizes generated.
// An optional `crop` ({ left, top, width, height } in source pixels) cuts a detail out first.
import sharp from 'sharp'
import { mkdir } from 'node:fs/promises'

const images = [
  { source: 'hero-img.jpg', name: 'hero', widths: [800, 1200, 1800] },
  { source: 'contact-img.jpg', name: 'contact', widths: [1200, 2000, 2800] },
  // Generated by `npm run bear` from bear.png: the body and the raised paw, as same-size layers.
  { source: 'bear-body.png', name: 'bear-body', widths: [260, 520] },
  { source: 'bear-paw.png', name: 'bear-paw', widths: [260, 520] },
  { source: 'portrait.png', name: 'portrait', widths: [320, 640] },
  { source: 'city-insight-home.png', name: 'city-insight-home', widths: [1200, 2400] },
  { source: 'city-insight-cities.png', name: 'city-insight-cities', widths: [1200, 2400] },
  // A single city card from the grid, used as a detail beside the lead screenshot.
  { source: 'city-insight-cities.png', name: 'city-insight-card', widths: [700], crop: { left: 404, top: 620, width: 682, height: 530 } },
  { source: 'city-insight-compare.png', name: 'city-insight-compare', widths: [1000, 2000] },
  { source: 'city-insight-compare.png', name: 'city-insight-radar', widths: [700], crop: { left: 1000, top: 1030, width: 880, height: 600 } },
  // The livability weights from the live methodology page, beside the case study's data section.
  { source: 'city-insight-livability.png', name: 'city-insight-livability', widths: [700, 1200] },
  { source: 'city-insight-ci-runs.png', name: 'city-insight-ci-runs', widths: [1000, 2000] },
  { source: 'city-insight-ask-ai.png', name: 'city-insight-ask-ai', widths: [1000, 2000] },
  { source: 'redevs-home.png', name: 'redevs-home', widths: [1000, 2000] },
]

await mkdir('public/images', { recursive: true })

for (const { source, name, widths, crop } of images) {
  let input = sharp(`image-sources/${source}`).rotate()
  if (crop) input = sharp(await input.extract(crop).toBuffer())
  const { width: originalWidth, height: originalHeight } = await input.metadata()
  for (const width of widths) {
    const output = `public/images/${name}-${width}.webp`
    await input.clone().resize({ width: Math.min(width, originalWidth) }).webp({ quality: 78 }).toFile(output)
  }
  console.log(`${name}: ${originalWidth}×${originalHeight} → ${widths.join(', ')}w`)
}
